---
document:
  import: meta-base.yml
  patch:
    approvals_adjustable_vertical_space: '-8.5em'
    approvals_department_value: ABC
    approvals_strategy: unknown
    bookmatter_path: bookmatter.tex.in
    driver_path: driver.tex.in
    footer_outer_field_normal_pages: \theMetaPageNumPrefix { } \thepage { } / \pageref{LastPage}
    header_id: P99999
    header_date: PUBLICATIONDATE
    metadata_path: metadata.tex.in
    publisher_path: publisher.tex.in
    setup_path: setup.tex.in
    table_caption_below: true
    table_uglify: false
    toc_level: 2
    list_of_figures: ''  # empty string to enable lof
    list_of_tables: '%'  # empty string to enable lot
