---
document:
  common:
    approvals_adjustable_vertical_space: '2.5em'
    approvals_date_and_signature_label: Date and Signature
    approvals_name_label: Name
    approvals_role_label: Approvals
    bold_font: ITCFranklinGothicStd-Demi
    bold_italic_font: ITCFranklinGothicStd-DemiIt
    change_log_author_label: Author
    change_log_date_label: Date
    change_log_description_label: Description
    change_log_issue_label: Iss.
    change_log_revision_label: Rev.
    chosen_logo: /opt/logo/liitos-logo.png
    code_fontsize: \scriptsize
    fixed_font_package: sourcecodepro
    font_path: /opt/fonts/
    font_suffix: .otf
    footer_frame_note: null
    footer_outer_field_normal_pages: \theMetaPageNumPrefix { } \thepage { } / \pageref{LastPage}
    footer_page_number_prefix: Page
    has_approvals: true
    has_changes: true
    has_notices: true
    header_date: null
    header_date_enable_auto: true
    header_date_label: 'Date:'
    header_date_show: true
    header_id: null
    header_id_label: 'Doc. ID:'
    header_id_show: true
    header_issue_revision_combined: null
    header_issue_revision_combined_label: 'Issue, Revision:'
    header_issue_revision_combined_show: true
    header_title: null
    header_type: Engineering Document
    issue: '01'
    italic_font: ITCFranklinGothicStd-BookIt
    list_of_figures: '%'  # empty string to enable lof
    list_of_tables: '%'  # empty string to enable lot
    main_font: ITCFranklinGothicStd-Book
    proprietary_information: /opt/legal/proprietary-information.txt
    revision: '00'
    sub_title: ' '
    title: null
    toc_level: 2
